train_dataset:
  type: Dataset
  dataset_root: data/dataset1/
  train_path: data/dataset1/train_list.txt
  num_classes: 2
  transforms:
#    - type: Resize
#      target_size: [ 512, 512 ]
    - type: ResizeStepScaling
      min_scale_factor: 0.8
      max_scale_factor: 1.2
      scale_step_size: 0.2
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomBlur
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize

  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/dataset1/
  val_path: data/dataset1/val_list.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val

batch_size: 4
iters: 300000

model:
  type: SegFormer_B2
  num_classes: 2
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/mix_vision_transformer_b2.tar.gz

#optimizer:
#  type: AdamW
#  beta1: 0.9
#  beta2: 0.999
#  weight_decay: 0.01
optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  power: 1


loss:
  types:
    - type: DiceLoss
  coef: [1]




test_config:
    is_slide: True
    crop_size: [512, 512]
    stride: [384, 384]
